---
Name: 'bfgoogleanalytics'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - BigforkGoogleAnalytics\GoogleConfig
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - BigforkGoogleAnalytics\GoogleLogger
